### ISSUE TITLE
BabelNet 3.6

### ISSUE THREAD

**Issue by marlonsvl** [pippokill/lesk-wsd-dsm#2]
Hello, I'm trying to prove with BabelNet 3.6 but not work, the error is: "Could not init BabelNet: read past EOF". May you help me, please

Thanks

**Comment by pippokill** [comment]
Hi,
the API for BabelNet 3.6 is completely different from the one used in the project. Some time ago I tried to change the code to support the new version, you can find a branch named BabelNet36.
Please, make sure you have properly configured the Babelnet API and copied the Babelnet resource folder properly.
